# Generated by Django 2.2.3 on 2019-07-14 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_auto_20180416_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lastdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 13, 30, 10, 775095)),
        ),
    ]
